# Generated by Django 2.0 on 2018-08-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Repository.BaseContent')),
                ('rep_id', models.CharField(blank=True, max_length=8000, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('rep_image', models.ImageField(blank=True, null=True, upload_to='Images/%Y/%m/%d')),
                ('rep_audio', models.FileField(blank=True, null=True, upload_to='Audios/%Y/%m/%d')),
                ('rep_video', models.FileField(blank=True, null=True, upload_to='Videos/%Y/%m/%d')),
            ],
            bases=('Repository.basecontent',),
        ),
    ]
