# Generated by Django 2.0 on 2018-08-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0002_auto_20180809_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Repository.BaseContent')),
                ('otp_number', models.CharField(blank=True, max_length=250, null=True)),
                ('otp_verify', models.BooleanField(default=False)),
            ],
            bases=('Repository.basecontent',),
        ),
        migrations.CreateModel(
            name='RepositoryUser',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Repository.BaseContent')),
                ('mobile_no', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('Repository.basecontent',),
        ),
        migrations.AddField(
            model_name='otp',
            name='repo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Repository.RepositoryUser'),
        ),
    ]
