# Generated by Django 2.0 on 2018-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0004_repositoryuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfiles',
            name='repo_document',
            field=models.FileField(blank=True, null=True, upload_to='Documents/%Y/%m/%d'),
        ),
    ]
